what is pandas?
pandas is a pthon library used for analizing , cleaning and manipulating structured data in tabular form.

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#import pandas
import  pandas as pd

In [ ]:
pd.__version__#check installed pandas version

'2.2.2'

**what is data frame?**

A DataFrame in pandas is a 2-dimensional table-like data structure used to store and work with data.

1. CREATE DATAFRAME

In [ ]:
# Using a list
df = pd.DataFrame([11,22,33], columns=['col_Name'])
print(df)

   col_Name
0        11
1        22
2        33

In [ ]:
print(type(df)) #check data type

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#using dictionary of lists
data = {'Name':['Madhav', 'Vishakha', 'Lalita', 'Hrishabh'],'age': [16,17,18,19],'salary':[90000, 70000, 80000,50000]}

In [ ]:
df = pd.DataFrame(data)
print(df)

       Name  age  salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   80000
3  Hrishabh   19   50000

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

2. BASIC DATAFRAME UNDERSTANDING

In [ ]:
df.head(2) # top rows

       Name  age  salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [ ]:
df.tail(2) #last rows

       Name  age  salary
2    Lalita   18   80000
3  Hrishabh   19   50000

In [ ]:
df.shape #return a tuple containingthe shape of the data frame - rows and columns

(4, 3)

In [ ]:
df.columns #list of columns names in data frame

Index(['Name', 'age', 'salary'], dtype='object')

In [ ]:
df.rename(columns={'salary': 'Monthly_salary'}, inplace=True) # rename column name/s

In [ ]:
df

       Name  age  Monthly_salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df

       Name  age  Monthly_salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df.info() #info method prints information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe() #describe method generates descriptive statistics of dataframe,only for numerical values

             age  Monthly_salary
count   4.000000        4.000000
mean   17.500000    72500.000000
std     1.290994    17078.251277
min    16.000000    50000.000000
25%    16.750000    65000.000000
50%    17.500000    75000.000000
75%    18.250000    82500.000000
max    19.000000    90000.000000

3. SAVE AND LOAD DATA FROM CSV

In [ ]:
df.to_csv('Test_data.csv', index=False) #save file- export data frame

In [ ]:
load_df= pd.read_csv('Test_data.csv')# load file - import data frame
load_df

       Name  age  Monthly_salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           80000
3  Hrishabh   19           50000

4. ROWS & COLUMNS - SELECTION

In [ ]:
#SELECT single column
df[['Name']]

       Name
0    Madhav
1  Vishakha
2    Lalita
3  Hrishabh

In [ ]:
#select multiple columns
df[['Name','Monthly_salary']]

       Name  Monthly_salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           80000
3  Hrishabh           50000

In [ ]:
#select single row // loc - Lable based index
df.loc[df.Name=='Madhav']

     Name  age  Monthly_salary
0  Madhav   16           90000

5. FILTER  DATAFRAME

In [ ]:
df

       Name  age  Monthly_salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df_age_filter = df[df['age'] >= 18] #filter and store dataframe in a new variable
df_age_filter

       Name  age  Monthly_salary
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df_age_filter

       Name  age  Monthly_salary
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df[(df['age'] >= 18) & (df['Monthly_salary'] >= 50000)] # multiple filter condition

       Name  age  Monthly_salary
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
df.where(df['age'] >= 18) #where function replace values in a dataframe based on a condition

       Name   age  Monthly_salary
0       NaN   NaN             NaN
1       NaN   NaN             NaN
2    Lalita  18.0         80000.0
3  Hrishabh  19.0         50000.0

In [ ]:
df.where(df['age'] >= 18, other = 'Not Eligible')

           Name           age Monthly_salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          80000
3      Hrishabh            19          50000

6. ROW AND COLUMN - OPERATION (ADD, update , delete)

In [ ]:
df

       Name  age  Monthly_salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           80000
3  Hrishabh   19           50000

In [ ]:
#create a new column
df['team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  age  Monthly_salary team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           80000  CTO
3  Hrishabh   19           50000   DA

In [ ]:
#add new column using existing column/s
df['Bonus'] = df['Monthly_salary'] * 0.20
df

       Name  age  Monthly_salary team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           80000  CTO  16000.0
3  Hrishabh   19           50000   DA  10000.0

In [ ]:
#add new row - at the end of data frame
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  age  Monthly_salary team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           80000  CTO  16000.0
3  Hrishabh   19           50000   DA  10000.0
4       ABC   21           21000   IT   2000.0

In [ ]:
#update value in dataframe using index-name
df.loc[0, 'Monthly_salary'] = 95000
df

       Name  age  Monthly_salary team    Bonus
0    Madhav   16           95000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           80000  CTO  16000.0
3  Hrishabh   19           50000   DA  10000.0
4       ABC   21           21000   IT   2000.0

In [ ]:
#update value in dataframe using column-value
df.loc[df.Name=='Madhav','Monthly_salary'] = 90000
df

       Name  age  Monthly_salary team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           80000  CTO  16000.0
3  Hrishabh   19           50000   DA  10000.0
4       ABC   21           21000   IT   2000.0

In [ ]:
#delete value - rows and columns

In [ ]:
#delete row using column - value filter
df = df.drop(df[df.Name == 'ABC'].index) #delete row, axis=0

In [ ]:
#delete row using index-name filter
df.drop(1, axis=0)

       Name  age  Monthly_salary team    Bonus
0    Madhav   16           90000  CEO  18000.0
2    Lalita   18           80000  CTO  16000.0
3  Hrishabh   19           50000   DA  10000.0

In [ ]:
df.drop('Bonus', axis=1, inplace=True) #delete one columns
#df.drop(['Bonus', 'team], axis=1, inplace=True) #delete multiple columns

In [ ]:
df

       Name  age  Monthly_salary team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           80000  CTO
3  Hrishabh   19           50000   DA

In [ ]:
df.rename(columns={'Monthly_salary': 'salary'}, inplace=True) #rename column name

In [ ]:
#sort values - order values in dataframe by asc or desc order
df.sort_values('salary') #ascending order , by default

       Name  age  salary team
3  Hrishabh   19   50000   DA
1  Vishakha   17   70000   HR
2    Lalita   18   80000  CTO
0    Madhav   16   90000  CEO

In [ ]:
df.sort_values('salary') #ascending order , by default

       Name  age  salary team
3  Hrishabh   19   50000   DA
1  Vishakha   17   70000   HR
2    Lalita   18   80000  CTO
0    Madhav   16   90000  CEO

7. WORKING WITH DATA VALUE

In [ ]:
#create a  data column - data of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

       Name  age  salary team         DOJ
0    Madhav   16   90000  CEO  2024-01-01
1  Vishakha   17   70000   HR  2024-01-15
2    Lalita   18   80000  CTO  2024-03-28
3  Hrishabh   19   50000   DA  2024-03-03

In [ ]:
df['DOJ'].dtype #object - type value

dtype('O')

In [ ]:
df['DOJ'] = pd.to_datetime(df['DOJ']) #change to date- time type

In [ ]:
df['DOJ'].dtype #date-time type

dtype('<M8[ns]')

In [ ]:
df1=df

In [ ]:
df['DOJ2'] = ['2024-01-02','2024-01-08','2024-05-30','2024-02-05']
df

       Name  age  salary team        DOJ        DOJ2
0    Madhav   16   90000  CEO 2024-01-01  2024-01-02
1  Vishakha   17   70000   HR 2024-01-15  2024-01-08
2    Lalita   18   80000  CTO 2024-03-28  2024-05-30
3  Hrishabh   19   50000   DA 2024-03-03  2024-02-05

In [ ]:
df['DOJ']+ pd.Timedelta(days=90)#add 90 days to doj column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[ns]

 8. HANDLING MISSING VALUES

In [ ]:
df

       Name  age  salary team        DOJ        DOJ2
0    Madhav   16   90000  CEO 2024-01-01  2024-01-02
1  Vishakha   17   70000   HR 2024-01-15  2024-01-08
2    Lalita   18   80000  CTO 2024-03-28  2024-05-30
3  Hrishabh   19   50000   DA 2024-03-03  2024-02-05

In [ ]:
df.isnull() # detect missing value

    Name    age  salary   team    DOJ   DOJ2
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [ ]:
import numpy as np # to create null values below

In [ ]:
df.loc[df.Name== 'hrishabh','salary'] = np.nan